language: go
go:
- 1.11.x
env:
- GO111MODULE=on

install:
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls

script:
- go build .
- go test -v -covermode=count -coverprofile=coverage.out
- $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
